### ISSUE TITLE
line numbers

### ISSUE THREAD

**Issue by okonon** [evanshortiss/fhlog#11]
Hello Evan,
I have a quick question. How easy will it be to log line numbers too? does it make sense to log them? I think it would be nice to have when looking at remote error logs.

Awesome job on fhlog!

Thanks

**Comment by evanshortiss** [comment]
It's possible. Although I'd need to research the best approach to doing so. I know _new Error().stack_ can be used to find a line number but it's an expensive call (I think, I have no proof right now but I read before that stack generation isn't cheap!) so it'd be best if line numbers should be an optional config for Logger instances.

Good idea overall, it's something we've used in internal logging solutions at work and is useful.

If you have any work done a PR is welcome. I'll look into it too.
