### ISSUE TITLE
Angular support

### ISSUE THREAD

**Issue by softBarbarian** [evanshortiss/fhlog#9]
Hello, awesome job!
Are there plans to support Angular?

**Comment by evanshortiss** [comment]
Thanks,

Technically it's compatible with Angular but would it be useful if it was possible to inject it as an Angular module without making the _fhlog_ a global variable on window?

So something like this?

```javascript
angular.module('myApp', ['fhlog']);
```

**Comment by evanshortiss** [comment]
@softBarbarian I'll implement this soon if you think it's appropriate. Also, feel free to contribute this if you like.

**Comment by evanshortiss** [comment]
You can now inject this as a dependency with Angular as shown in the updated README. Check it out and let me know if any problems arise.

**Comment by softBarbarian** [comment]
w00t! This is awesome!
How difficult it will be to make it work on sever side too?

Keep up the good work!

**Comment by evanshortiss** [comment]
PS: This already works on the server (Node.js)

**Comment by softBarbarian** [comment]
Yeah! I know!
Exude my stupidity!
PS. Red the description!
